# Netlify configuration for a static SPA portfolio.
# Adjust `publish` and `command` to match your build tool (e.g. "dist" for Vite, "build" for CRA).

[build]
    command = "npm run build"
    publish = "dist"
    functions = "netlify/functions"
    environment = { NODE_VERSION = "18" }

[context.production.environment]
    NODE_ENV = "production"

[context.deploy-preview.environment]
    NODE_ENV = "development"

# SPA fallback: serve index.html for all routes (client-side routing)
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    force = true

# Example function route mapping (uncomment/adjust if using functions)
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200

# Security and performance headers
[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "strict-origin-when-cross-origin"
        X-XSS-Protection = "1; mode=block"
        Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
        Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.example.com;"

# Long-term caching for immutable assets
[[headers]]
    for = "/assets/*"
    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"